CUDA_VISIBLE_DEVICES=0 python train.py \
    --domain_name cartpole \
    --task_name swingup \
    --encoder_type pixel \
    --action_repeat 8 \
    --proto_mem_capacity 150 \
    --lambda_ent 0.5 \
    --lambda_new 0.5 \
    --lambda_con 1.0 \
    --save_tb --save_model --save_video --pre_transform_image_size 100 --image_size 84 \
    --work_dir ./tmp/cartpole \
    --agent curl_oupn --frame_stack 3 \
    --seed 1234 --critic_lr 1e-3 --actor_lr 1e-3 --eval_freq 2500 --batch_size 512 --num_train_steps 12500 --init_steps 512
